name: Build-SonOyuncu-Blink
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3
    - name: Download WinDivert
      run: |
        curl -L https://github.com/basil00/WinDivert/releases/download/v2.2.2/WinDivert-2.2.2-A.zip -o wd.zip
        expand-archive wd.zip -destinationpath wd
    - name: Compile
      run: |
        cl.exe /EHsc /I wd/WinDivert-2.2.2-A/include main.cpp /link /LIBPATH:wd/WinDivert-2.2.2-A/x64 WinDivert.lib /OUT:SonOyuncuBlink.exe
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SonOyuncu-Blink-EXE
        path: |
          SonOyuncuBlink.exe
          wd/WinDivert-2.2.2-A/x64/WinDivert64.sys
          wd/WinDivert-2.2.2-A/x64/WinDivert.dll
          
